### ISSUE TITLE
move to webpack

### ISSUE THREAD

**Issue by DanielRuf** [asyncdesign/webui#212]
Grunt has some issues and the future is webpack / Rollup.

**Comment by asyncdesign** [comment]
Great idea. Webpack should be added.

**Comment by DanielRuf** [comment]
If you need help I can migrate the Gruntfile to a webpack config and create a PR.

**Comment by asyncdesign** [comment]
Thanks Daniel. I would be happy for you to work on this and open a PR.

**Comment by asyncdesign** [comment]
I have bumped the target version for this work to v6.4.0 to give more time. Most important for me is that it should work well with plain javascript frameworks such as Vue.js.  Would like to support module loading for javascript and CSS files, but support for TypeScript will be much later in the future, if we do it at all. If it can work for Angular 2+ that would be great, but may need typings file for that? Thoughts?

**Comment by DanielRuf** [comment]
I guess I'll plan to do the migration to a webpack config this weekend. Is this ok?

**Comment by asyncdesign** [comment]
Very much appreciated Daniel. Don't feel the need to rush it as we have time - not expecting it to be done in a week. Even just migrating the tasks would be a good first step. There's likely to be a lot going on over the next few months with the framework and documentation, as we try to move it forward. It may turn into a major release v7.0.0, but have to see how it develops.

**Comment by asyncdesign** [comment]
I have merged in webpack and all looks fine. Great work!

**Comment by DanielRuf** [comment]
Great thanks. If there are any issues related to this or needed changes, please let me know. I will take a look then and provide a solution and extend the webpack config.
