### ISSUE TITLE
huge images

### ISSUE THREAD

**Issue by DanielRuf** [asyncdesign/webui#220]
The images in /images and /docs/assets/images are really big. Instead of png (there is no transparency needed) they should be jpeg and compressed / optimized.

The repository is unnecessary big because of this.

**Comment by asyncdesign** [comment]
That's very true. The images will be cleared away as part of the documentation re-work. The plan is to use live code examples instead of images within the site.

**Comment by asyncdesign** [comment]
Unused images have been removed from the WebUI package. Also, converted all to .jpg and resized where appropriate. The images contained in docs will be addressed as part of the documentation re-work.

**Comment by DanielRuf** [comment]
Ok. Thanks for the update. I will checkout the changes and check against my image optimization workflow.

**Comment by asyncdesign** [comment]
Completed.
